# A function to convert 2- and 4-digit FOE (text) to custom foe_census codes


convert_foe_census <- function(x) {
  
  case_when(
    x == "Natural and Physical Sciences"                                ~ "Science",
    x == "Information Technology"                                       ~ "IT",
    x == "Engineering and Related Technologies"                         ~ "Engineering",
    x == "Architecture and Building"                                    ~ "Architecture",
    x == "Agriculture, Environmental and Related Studies"               ~ "Agriculture",
    x == "Health"                                                       ~ "not_used",
    x == "Education"                                                    ~ "Education",
    x == "Management and Commerce"                                      ~ "Commerce",
    x == "Society and Culture"                                          ~ "not_used",
    x == "Creative Arts"                                                ~ "not_used",
    x == "Food, Hospitality and Personal Services"                      ~ "Hospitality",
    x == "Mixed Field Programmes"                                       ~ "not_used",
    x == "Field of study inadequately described"                        ~ "not_used",
    x == "Field of study not stated"                                    ~ "not_used",
    x == "Not applicable"                                               ~ "Not applicable",
    x == "Natural and Physical Sciences, nfd"                           ~ "not_used",
    x == "Mathematical Sciences"                                        ~ "not_used",
    x == "Physics and Astronomy"                                        ~ "not_used",
    x == "Chemical Sciences"                                            ~ "not_used",
    x == "Earth Sciences"                                               ~ "not_used",
    x == "Biological Sciences"                                          ~ "not_used",
    x == "Other Natural and Physical Sciences"                          ~ "not_used",
    x == "Information Technology, nfd"                                  ~ "not_used",
    x == "Computer Science"                                             ~ "not_used",
    x == "Information Systems"                                          ~ "not_used",
    x == "Other Information Technology"                                 ~ "not_used",
    x == "Engineering and Related Technologies, nfd"                    ~ "not_used",
    x == "Manufacturing Engineering and Technology"                     ~ "not_used",
    x == "Process and Resources Engineering"                            ~ "not_used",
    x == "Automotive Engineering and Technology"                        ~ "not_used",
    x == "Mechanical and Industrial Engineering and Technology"         ~ "not_used",
    x == "Civil Engineering"                                            ~ "not_used",
    x == "Geomatic Engineering"                                         ~ "not_used",
    x == "Electrical and Electronic Engineering and Technology"         ~ "not_used",
    x == "Aerospace Engineering and Technology"                         ~ "not_used",
    x == "Maritime Engineering and Technology"                          ~ "not_used",
    x == "Other Engineering and Related Technologies"                   ~ "not_used",
    x == "Architecture and Building, nfd"                               ~ "not_used",
    x == "Architecture and Urban Environment"                           ~ "not_used",
    x == "Building"                                                     ~ "not_used",
    x == "Agriculture, Environmental and Related Studies, nfd"          ~ "not_used",
    x == "Agriculture"                                                  ~ "not_used",
    x == "Horticulture and Viticulture"                                 ~ "not_used",
    x == "Forestry Studies"                                             ~ "not_used",
    x == "Fisheries Studies"                                            ~ "not_used",
    x == "Environmental Studies"                                        ~ "not_used",
    x == "Other Agriculture, Environmental and Related Studies"         ~ "not_used",
    x == "Health, nfd"                                                  ~ "Other medical",
    x == "Medical Studies"                                              ~ "Medicine",
    x == "Nursing"                                                      ~ "Nursing",
    x == "Pharmacy"                                                     ~ "Other medical",
    x == "Dental Studies"                                               ~ "Other medical",
    x == "Optical Science"                                              ~ "Other medical",
    x == "Veterinary Studies"                                           ~ "Other medical",
    x == "Public Health"                                                ~ "Other health",
    x == "Radiography"                                                  ~ "Other medical",
    x == "Rehabilitation Therapies"                                     ~ "Other health",
    x == "Complementary Therapies"                                      ~ "Other health",
    x == "Other Health"                                                 ~ "Other health",
    x == "Education, nfd"                                               ~ "not_used",
    x == "Teacher Education"                                            ~ "not_used",
    x == "Curriculum and Education Studies"                             ~ "not_used",
    x == "Other Education"                                              ~ "not_used",
    x == "Management and Commerce, nfd"                                 ~ "not_used",
    x == "Accounting"                                                   ~ "not_used",
    x == "Business and Management"                                      ~ "not_used",
    x == "Sales and Marketing"                                          ~ "not_used",
    x == "Tourism"                                                      ~ "not_used",
    x == "Office Studies"                                               ~ "not_used",
    x == "Banking, Finance and Related Fields"                          ~ "not_used",
    x == "Other Management and Commerce"                                ~ "not_used",
    x == "Society and Culture, nfd"                                     ~ "Humanities",
    x == "Political Science and Policy Studies"                         ~ "Humanities",
    x == "Studies in Human Society"                                     ~ "Humanities",
    x == "Human Welfare Studies and Services"                           ~ "Humanities",
    x == "Behavioural Science"                                          ~ "Psychology",
    x == "Law"                                                          ~ "Law",
    x == "Justice and Law Enforcement"                                  ~ "Law",
    x == "Librarianship, Information Management and Curatorial Studies" ~ "Humanities",
    x == "Language and Literature"                                      ~ "Humanities",
    x == "Philosophy and Religious Studies"                             ~ "Humanities",
    x == "Economics and Econometrics"                                   ~ "Commerce",
    x == "Sport and Recreation"                                         ~ "Sport",
    x == "Other Society and Culture"                                    ~ "Humanities",
    x == "Creative Arts, nfd"                                           ~ "Performing arts",
    x == "Performing Arts"                                              ~ "Performing arts",
    x == "Visual Arts and Crafts"                                       ~ "Performing arts",
    x == "Graphic and Design Studies"                                   ~ "Graphic studies",
    x == "Communication and Media Studies"                              ~ "Communication",
    x == "Other Creative Arts"                                          ~ "Performing arts",
    x == "Food, Hospitality and Personal Services, nfd"                 ~ "not_used",
    x == "Food and Hospitality"                                         ~ "not_used",
    x == "Personal Services"                                            ~ "not_used",
    x == "Mixed Field Programmes, nfd"                                  ~ "not_used",
    x == "General Education Programmes"                                 ~ "not_used",
    x == "Social Skills Programmes"                                     ~ "not_used",
    x == "Employment Skills Programmes"                                 ~ "not_used",
    x == "Other Mixed Field Programmes"                                 ~ "not_used")
}
